services:
  cosy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cosy
    environment:
      - is_half=True
      - is_share=True
    ports:
      - "6010:6010"
      - "6011:6011"
    shm_size: 16G
    deploy:
      resources:
        limits:
          cpus: '8'
        reservations:
          devices:
          - driver: nvidia
            count: "all"
            capabilities: [gpu]
    stdin_open: true
    tty: true
    restart: unless-stopped

