version: '3.7'
services:
  cosy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cosy
    ports:
      - "6010:6010"
      - "6011:6011"
    deploy:
      resources:
        limits:
          cpus: '16'
    restart: unless-stopped
